iowa_liquor_warehouse:
  outputs:
    dev:
      type: "{{ env_var('DBW_TYPE', 'bigquery')}}"
      method: service-account
      keyfile: "{{ env_var('DBW_KEYFILE', '/usr/local/airflow/iowa_liquor_warehouse/dbt-user-creds.json')}}"
      project: teak-mantis-321715
      dataset: iowa_liquor_warehouse
      threads: 1
      location: US
      priority: interactive
  target: dev

covid_19_warehouse:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: covid19
      schema: public
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
  target: dev