
SELECT {{ to_date('"fecha reporte web"') }} as report_date, 
       "ID de caso" as event_id, 
       {{ to_date('"Fecha de notificación"') }} as ack_date, 
       "Código DIVIPOLA departamento" as state_id, 
       "Nombre departamento" as state_name, 
       "Código DIVIPOLA municipio" as city_id, 
       "Nombre municipio" as city_name, 
       "Edad" as age, 
       "Unidad de medida de edad" age_measure, 
       CASE WHEN "Sexo" = 'M' THEN 'MALE' ELSE 'FEMALE' END as genre, 
       "Tipo de contagio" as contagious_type, 
       "Ubicación del caso" as event_location, 
       "Estado" as status_name, 
       "Código ISO del país" as origin_country_id, 
       "Nombre del país" as origin_country_name, 
       "Recuperado" as recovered, 
       {{ to_date('"Fecha de inicio de síntomas"') }} as symptons_date, 
       {{ to_date('"Fecha de muerte"') }} as death_date, 
       {{ to_date('"Fecha de diagnóstico"') }} as diagnostic_date, 
       {{ to_date('"Fecha de recuperación"') }} as recovered_date, 
       "Tipo de recuperación" as recovered_type, 
       "Pertenencia étnica" as etnic, 
       "Nombre del grupo étnico" as etnic_name
FROM {{ source('covid19_seeds', 'covid_19_source')}}